services:
  app:
    container_name: go-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app:cached     
    networks:
      - go-network
    command: air -c .air.toml

volumes:
  air-tmp:

networks:
  go-network:
