FROM golang:1.24-alpine

RUN apk add --no-cache git bash curl gcc musl-dev libc6-compat

RUN go install github.com/air-verse/air@latest

ENV CGO_ENABLED=1

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

CMD ["air", "-c", ".air.toml"]
