services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: go-api-vagas
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ENV=production
      - PORT=8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge